version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: make
      - run: chmod +x test_script.sh
      - run: ./test_script.sh
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
      - run: chmod +x test_script.sh
      - run: ./test_script.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest